### ISSUE TITLE
Indentation error in transcript file

### ISSUE THREAD

**Issue by Avadhoot4757** [Avadhoot4757/SE_assignment#3]
review and update transcript file
![Screenshot from 2024-10-16 14-54-17](https://github.com/user-attachments/assets/99d4f536-1907-4240-83e4-2e424fcdc867)

**Comment by AdityaGund** [comment]
ohh i willl take it ....

**Comment by PramodDudhal** [comment]
i will solve the issue

**Comment by PramodDudhal** [comment]
proper indentation in given
